
import type { TourPackage, TripDay, TripLocation, Booking, Review, Activity } from './types';

// Helper to generate IDs
const generateId = () => Math.random().toString(36).substr(2, 9);

export const mockTripLocations: TripLocation[] = [
  {
    id: 'loc_everest_base',
    name: 'Everest Base Camp',
    latitude: 27.9881,
    longitude: 86.9250,
    place_type: 'mountain',
    country: 'Nepal',
    state: 'Province No. 1',
    district: 'Solukhumbu',
    city: 'Khumbu',
    code: 'EBC',
    description: 'The starting point for many treks to Mount Everest.',
    address: 'Everest Base Camp, Khumbu, Nepal',
    image_urls: ['https://picsum.photos/seed/loc1/400/300', 'https://picsum.photos/seed/loc1-2/400/300'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
    {
    id: 'loc_goa_beach',
    name: 'Calangute Beach',
    latitude: 15.548,
    longitude: 73.759,
    place_type: 'beach',
    country: 'India',
    state: 'Goa',
    district: 'North Goa',
    city: 'Calangute',
    code: 'GOA-CAL',
    description: 'Famous for its vibrant nightlife and serene beaches.',
    address: 'Calangute Beach, Goa, India',
    image_urls: ['https://picsum.photos/seed/loc2/400/300', 'https://picsum.photos/seed/loc2-2/400/300'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'loc_jaipur_city_palace',
    name: 'Jaipur City Palace',
    latitude: 26.9258,
    longitude: 75.8237,
    place_type: 'heritage',
    country: 'India',
    state: 'Rajasthan',
    district: 'Jaipur',
    city: 'Jaipur',
    code: 'JAI-CP',
    description: 'A palace complex in Jaipur, the capital of the Rajasthan state.',
    address: 'Tulsi Marg, Gangori Bazaar, J.D.A. Market, Pink City, Jaipur, Rajasthan 302002, India',
    image_urls: ['https://picsum.photos/seed/loc3/400/300'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'loc_jodhpur_mehrangarh',
    name: 'Mehrangarh Fort',
    latitude: 26.2979,
    longitude: 73.0189,
    place_type: 'heritage',
    country: 'India',
    state: 'Rajasthan',
    district: 'Jodhpur',
    city: 'Jodhpur',
    code: 'JOD-MF',
    description: 'One of the largest forts in India, built in around 1459.',
    address: 'Sodagaran Mohalla, Jodhpur, Rajasthan 342001, India',
    image_urls: ['https://picsum.photos/seed/loc4/400/300'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'loc_udaipur_lake_pichola',
    name: 'Lake Pichola',
    latitude: 24.5707,
    longitude: 73.6749,
    place_type: 'nature',
    country: 'India',
    state: 'Rajasthan',
    district: 'Udaipur',
    city: 'Udaipur',
    code: 'UDA-LP',
    description: 'An artificial fresh water lake, created in the year 1362 AD.',
    address: 'Lake Pichola, Udaipur, Rajasthan, India',
    image_urls: ['https://picsum.photos/seed/loc5/400/300'],
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
// THIS FILE IS NOW LARGELY DEPRECATED FOR TRIP DAYS.
// IT IS KEPT FOR OTHER MOCK DATA LIKE BOOKINGS, REVIEWS, etc.

export const mockTourPackages: any[] = [
  {
    id: 'pkg1',
    name: 'Everest Base Camp Trek',
    package_type: 'international',
    category: 'adventure',
    base_price: 2500,
    days: 14,
    nights: 13,
    created_at: new Date('2023-01-01'),
    withdrawalDate: new Date('2025-01-01'),
    max_guests: 15,
    itineraryId: 'itin1',
    image_urls: ['https://picsum.photos/seed/1/600/400'],
    pay_in_parts: [{ plan_name: 'Deposit', months: 0, monthly_payment: 500, total_amount: 500 }],
    description: 'A challenging and rewarding trek to the base of the world\'s highest mountain.',
    highlights: ['Stunning mountain views', 'Sherpa culture', 'Tengboche Monastery'],
    inclusion: 'Flights from Kathmandu to Lukla, Accommodation in tea houses, Licensed guide',
    exclusion: 'International airfare, Personal trekking gear, Tips for guides',
    booking_policy: 'A 20% deposit is required at the time of booking.',
    cancellation_policy: 'Cancellations made 30 days prior to departure are fully refundable.',
    terms_and_conditions: 'Travel insurance is mandatory for all participants.',
    is_featured: true,
    featured_image_url: 'https://picsum.photos/seed/2/1200/800',
    is_active: true,
    updated_at: new Date(),
  },
  {
    id: 'pkg2',
    name: 'Goa Beach Paradise',
    package_type: 'domestic',
    category: 'leisure',
    base_price: 800,
    days: 5,
    nights: 4,
    created_at: new Date('2023-03-01'),
    withdrawalDate: new Date('2024-12-31'),
    max_guests: 50,
    itineraryId: 'itin2',
    image_urls: ['https://picsum.photos/seed/3/600/400'],
    pay_in_parts: [],
    description: 'Relax and unwind on the beautiful beaches of Goa.',
    highlights: ['Pristine beaches', 'Vibrant nightlife', 'Portuguese architecture'],
    inclusion: 'Accommodation in a 4-star hotel, Daily breakfast, Airport transfers',
    exclusion: 'Airfare, Lunches and dinners, Watersports activities',
    booking_policy: 'Full payment is required at the time of booking.',
    cancellation_policy: 'Non-refundable.',
    terms_and_conditions: 'Subject to availability.',
    is_featured: false,
    featured_image_url: '',
    is_active: true,
    updated_at: new Date(),
  },
    {
    id: 'pkg3',
    name: 'Cultural Rajasthan',
    package_type: 'domestic',
    category: 'cultural',
    base_price: 1200,
    days: 7,
    nights: 6,
    created_at: new Date('2023-02-15'),
    withdrawalDate: new Date('2025-02-14'),
    max_guests: 25,
    itineraryId: 'itin3',
    image_urls: ['https://picsum.photos/seed/4/600/400'],
    pay_in_parts: [],
    description: 'Explore the vibrant culture and majestic forts of Rajasthan.',
    highlights: ['Jaipur City Palace', 'Jodhpur Mehrangarh Fort', 'Udaipur Lake Pichola'],
    inclusion: 'Accommodation in heritage hotels, Private car and driver, Local guides',
    exclusion: 'Entrance fees to monuments, Meals, Flights',
    booking_policy: '50% payment to book.',
    cancellation_policy: 'Free cancellation up to 15 days before travel.',
    terms_and_conditions: 'Valid for Indian citizens only.',
    is_featured: true,
    featured_image_url: 'https://picsum.photos/seed/5/1200/800',
    is_active: false,
    updated_at: new Date(),
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'book1',
    tourPackageId: 'pkg1',
    userId: 'user1',
    customerName: 'Alice Johnson',
    customerEmail: 'alice@example.com',
    status: 'confirmed',
    paymentType: 'full',
    transactionId: 'txn_12345',
    reservationDate: new Date(),
    travelDate: new Date('2024-10-15'),
    referralCode: '',
    totalAmount: 2500,
    paidAmount: 2500,
    numberOfTravelers: 1,
    createdAt: new Date(),
  },
  {
    id: 'book2',
    tourPackageId: 'pkg2',
    userId: 'user2',
    customerName: 'Bob Smith',
    customerEmail: 'bob@example.com',
    status: 'pending',
    paymentType: 'partial',
    transactionId: 'txn_67890',
    reservationDate: new Date(),
    travelDate: new Date('2024-11-20'),
    referralCode: 'FRIEND10',
    totalAmount: 1600,
    paidAmount: 800,
    numberOfTravelers: 2,
    createdAt: new Date(),
  },
   {
    id: 'book3',
    tourPackageId: 'pkg2',
    userId: 'user3',
    customerName: 'Charlie Brown',
    customerEmail: 'charlie@example.com',
    status: 'completed',
    paymentType: 'full',
    transactionId: 'txn_abcde',
    reservationDate: new Date('2023-12-01'),
    travelDate: new Date('2024-01-10'),
    referralCode: '',
    totalAmount: 800,
    paidAmount: 800,
    numberOfTravelers: 1,
    createdAt: new Date('2023-12-01'),
  },
    {
    id: 'book4',
    tourPackageId: 'pkg3',
    userId: 'user4',
    customerName: 'Diana Prince',
    customerEmail: 'diana@example.com',
    status: 'cancelled',
    paymentType: 'partial',
    transactionId: 'txn_fghij',
    reservationDate: new Date('2024-02-01'),
    travelDate: new Date('2024-04-05'),
    referralCode: '',
    totalAmount: 2400,
    paidAmount: 1200,
    numberOfTravelers: 2,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'book5',
    tourPackageId: 'pkg1',
    userId: 'user5',
    customerName: 'Ethan Hunt',
    customerEmail: 'ethan@example.com',
    status: 'confirmed',
    paymentType: 'full',
    transactionId: 'txn_klmno',
    reservationDate: new Date(),
    travelDate: new Date('2024-10-15'),
    referralCode: '',
    totalAmount: 2500,
    paidAmount: 2500,
    numberOfTravelers: 1,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
  },
  {
    id: 'book6',
    tourPackageId: 'pkg2',
    userId: 'user6',
    customerName: 'Fiona Glenanne',
    customerEmail: 'fiona@example.com',
    status: 'confirmed',
    paymentType: 'full',
    transactionId: 'txn_pqrst',
    reservationDate: new Date(),
    travelDate: new Date('2024-11-20'),
    referralCode: '',
    totalAmount: 1600,
    paidAmount: 1600,
    numberOfTravelers: 2,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
  },
];

export const mockReviews: Review[] = [
  {
    id: 'rev1',
    tourPackageId: 'pkg2',
    userId: 'user3',
    customerName: 'Charlie Brown',
    rating: 5,
    reviewText: 'Absolutely fantastic trip! The beaches were pristine and the hotel was excellent. Highly recommended for a relaxing getaway.',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'rev2',
    tourPackageId: 'pkg1',
    userId: 'user7',
    customerName: 'Grace Lee',
    rating: 4,
    reviewText: 'The Everest trek was challenging but the views were worth every step. The guide was knowledgeable but some of the tea houses were very basic.',
    createdAt: new Date('2023-11-05'),
  },
    {
    id: 'rev3',
    tourPackageId: 'pkg3',
    userId: 'user8',
    customerName: 'Henry Wilson',
    rating: 3,
    reviewText: 'Interesting cultural tour, but it felt a bit rushed. We could have used more time at each fort. The heritage hotels were a nice touch.',
    createdAt: new Date('2024-03-10'),
  },
];

// Combine into a single export for easier importing
const mockData = {
    tourPackages: mockTourPackages,
    tripDays: [], // This is now handled by Supabase
    tripLocations: mockTripLocations,
    bookings: mockBookings,
    reviews: mockReviews,
};

export default mockData;

    
