import type { TourPackage, TripDay, TripLocation, Booking, Review, Activity } from './types';

// Helper to generate IDs
const generateId = () => Math.random().toString(36).substr(2, 9);

export const mockTripLocations: TripLocation[] = [
  {
    id: 'loc1',
    locationName: 'Himalayan Base Camp',
    latitude: 27.9881,
    longitude: 86.9250,
    type: 'mountain',
    country: 'Nepal',
    state: 'Province No. 1',
    district: 'Solukhumbu',
    city: 'Khumbu',
    code: 'HBC',
    description: 'The starting point for many treks to Mount Everest.',
    address: 'Everest Base Camp, Khumbu, Nepal',
    images: ['https://picsum.photos/seed/loc1/400/300', 'https://picsum.photos/seed/loc1-2/400/300'],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    id: 'loc2',
    locationName: 'Goa Beach',
    latitude: 15.300,
    longitude: 73.76,
    type: 'beach',
    country: 'India',
    state: 'Goa',
    district: 'North Goa',
    city: 'Calangute',
    code: 'GOA-BEACH',
    description: 'Famous for its vibrant nightlife and serene beaches.',
    address: 'Calangute Beach, Goa, India',
    images: ['https://picsum.photos/seed/loc2/400/300', 'https://picsum.photos/seed/loc2-2/400/300'],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockActivities: Activity[] = [
    {
        activityId: 'act1',
        name: 'Morning Trek to Viewpoint',
        type: 'trekking',
        time: '06:00 AM',
        duration: '3 hours',
        location: 'Himalayan Base Camp',
        locationId: 'loc1',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'An early morning trek to catch the sunrise over the Himalayas.',
    },
    {
        activityId: 'act2',
        name: 'Beachside Yoga',
        type: 'leisure',
        time: '07:00 AM',
        duration: '1 hour',
        location: 'Goa Beach',
        locationId: 'loc2',
        price: 20,
        priceIncluded: true,
        bookingRequired: true,
        description: 'A relaxing yoga session by the sea.',
    },
];

export const mockTripDays: TripDay[] = [
  {
    id: 'day1',
    dayName: 'Arrival and Acclimatization',
    dayNumber: 1,
    description: 'Arrive at the base camp and spend the day acclimatizing to the altitude.',
    specialInstructions: 'Drink plenty of water and avoid strenuous activity.',
    departureLocation: 'Kathmandu',
    numberOfStays: 1,
    tourPackageId: 'pkg1',
    activities: [mockActivities[0]],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'day2',
    dayName: 'Beach Day & Watersports',
    dayNumber: 1,
    description: 'Enjoy a full day at the famous beaches of Goa. Optional watersports available.',
    specialInstructions: 'Apply sunscreen liberally.',
    departureLocation: 'Goa Airport',
    numberOfStays: 2,
    tourPackageId: 'pkg2',
    activities: [mockActivities[1]],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];


export const mockTourPackages: TourPackage[] = [
  {
    id: 'pkg1',
    tourName: 'Everest Base Camp Trek',
    tourType: 'international',
    category: 'adventure',
    basePrice: 2500,
    days: 14,
    nights: 13,
    introductionDate: new Date('2023-01-01'),
    withdrawalDate: new Date('2025-01-01'),
    maxPermittedBooking: 15,
    itineraryId: 'itin1',
    imageUrl: 'https://picsum.photos/seed/1/600/400',
    payInParts: [{ partName: 'Deposit', durationMonths: 0, price: 500 }],
    description: 'A challenging and rewarding trek to the base of the world\'s highest mountain.',
    highlights: ['Stunning mountain views', 'Sherpa culture', 'Tengboche Monastery'],
    inclusions: ['Flights from Kathmandu to Lukla', 'Accommodation in tea houses', 'Licensed guide'],
    exclusions: ['International airfare', 'Personal trekking gear', 'Tips for guides'],
    bookingPolicies: 'A 20% deposit is required at the time of booking.',
    cancellationPolicies: 'Cancellations made 30 days prior to departure are fully refundable.',
    termsAndConditions: 'Travel insurance is mandatory for all participants.',
    isFeatured: true,
    featuredImageUrl: 'https://picsum.photos/seed/2/1200/800',
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'pkg2',
    tourName: 'Goa Beach Paradise',
    tourType: 'domestic',
    category: 'leisure',
    basePrice: 800,
    days: 5,
    nights: 4,
    introductionDate: new Date('2023-03-01'),
    withdrawalDate: new Date('2024-12-31'),
    maxPermittedBooking: 50,
    itineraryId: 'itin2',
    imageUrl: 'https://picsum.photos/seed/3/600/400',
    payInParts: [],
    description: 'Relax and unwind on the beautiful beaches of Goa.',
    highlights: ['Pristine beaches', 'Vibrant nightlife', 'Portuguese architecture'],
    inclusions: ['Accommodation in a 4-star hotel', 'Daily breakfast', 'Airport transfers'],
    exclusions: ['Airfare', 'Lunches and dinners', 'Watersports activities'],
    bookingPolicies: 'Full payment is required at the time of booking.',
    cancellationPolicies: 'Non-refundable.',
    termsAndConditions: 'Subject to availability.',
    isFeatured: false,
    featuredImageUrl: '',
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    id: 'pkg3',
    tourName: 'Cultural Rajasthan',
    tourType: 'domestic',
    category: 'cultural',
    basePrice: 1200,
    days: 7,
    nights: 6,
    introductionDate: new Date('2023-02-15'),
    withdrawalDate: new Date('2025-02-14'),
    maxPermittedBooking: 25,
    itineraryId: 'itin3',
    imageUrl: 'https://picsum.photos/seed/4/600/400',
    payInParts: [],
    description: 'Explore the vibrant culture and majestic forts of Rajasthan.',
    highlights: ['Jaipur City Palace', 'Jodhpur Mehrangarh Fort', 'Udaipur Lake Pichola'],
    inclusions: ['Accommodation in heritage hotels', 'Private car and driver', 'Local guides'],
    exclusions: ['Entrance fees to monuments', 'Meals', 'Flights'],
    bookingPolicies: '50% payment to book.',
    cancellationPolicies: 'Free cancellation up to 15 days before travel.',
    termsAndConditions: 'Valid for Indian citizens only.',
    isFeatured: true,
    featuredImageUrl: 'https://picsum.photos/seed/5/1200/800',
    status: 'inactive',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'book1',
    tourPackageId: 'pkg1',
    userId: 'user1',
    customerName: 'Alice Johnson',
    customerEmail: 'alice@example.com',
    status: 'confirmed',
    paymentType: 'full',
    transactionId: 'txn_12345',
    reservationDate: new Date(),
    travelDate: new Date('2024-10-15'),
    referralCode: '',
    totalAmount: 2500,
    paidAmount: 2500,
    numberOfTravelers: 1,
    createdAt: new Date(),
  },
  {
    id: 'book2',
    tourPackageId: 'pkg2',
    userId: 'user2',
    customerName: 'Bob Smith',
    customerEmail: 'bob@example.com',
    status: 'pending',
    paymentType: 'partial',
    transactionId: 'txn_67890',
    reservationDate: new Date(),
    travelDate: new Date('2024-11-20'),
    referralCode: 'FRIEND10',
    totalAmount: 1600,
    paidAmount: 800,
    numberOfTravelers: 2,
    createdAt: new Date(),
  },
   {
    id: 'book3',
    tourPackageId: 'pkg2',
    userId: 'user3',
    customerName: 'Charlie Brown',
    customerEmail: 'charlie@example.com',
    status: 'completed',
    paymentType: 'full',
    transactionId: 'txn_abcde',
    reservationDate: new Date('2023-12-01'),
    travelDate: new Date('2024-01-10'),
    referralCode: '',
    totalAmount: 800,
    paidAmount: 800,
    numberOfTravelers: 1,
    createdAt: new Date('2023-12-01'),
  },
    {
    id: 'book4',
    tourPackageId: 'pkg3',
    userId: 'user4',
    customerName: 'Diana Prince',
    customerEmail: 'diana@example.com',
    status: 'cancelled',
    paymentType: 'partial',
    transactionId: 'txn_fghij',
    reservationDate: new Date('2024-02-01'),
    travelDate: new Date('2024-04-05'),
    referralCode: '',
    totalAmount: 2400,
    paidAmount: 1200,
    numberOfTravelers: 2,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'book5',
    tourPackageId: 'pkg1',
    userId: 'user5',
    customerName: 'Ethan Hunt',
    customerEmail: 'ethan@example.com',
    status: 'confirmed',
    paymentType: 'full',
    transactionId: 'txn_klmno',
    reservationDate: new Date(),
    travelDate: new Date('2024-10-15'),
    referralCode: '',
    totalAmount: 2500,
    paidAmount: 2500,
    numberOfTravelers: 1,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
  },
  {
    id: 'book6',
    tourPackageId: 'pkg2',
    userId: 'user6',
    customerName: 'Fiona Glenanne',
    customerEmail: 'fiona@example.com',
    status: 'confirmed',
    paymentType: 'full',
    transactionId: 'txn_pqrst',
    reservationDate: new Date(),
    travelDate: new Date('2024-11-20'),
    referralCode: '',
    totalAmount: 1600,
    paidAmount: 1600,
    numberOfTravelers: 2,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
  },
];

export const mockReviews: Review[] = [
  {
    id: 'rev1',
    tourPackageId: 'pkg2',
    userId: 'user3',
    customerName: 'Charlie Brown',
    rating: 5,
    reviewText: 'Absolutely fantastic trip! The beaches were pristine and the hotel was excellent. Highly recommended for a relaxing getaway.',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'rev2',
    tourPackageId: 'pkg1',
    userId: 'user7',
    customerName: 'Grace Lee',
    rating: 4,
    reviewText: 'The Everest trek was challenging but the views were worth every step. The guide was knowledgeable but some of the tea houses were very basic.',
    createdAt: new Date('2023-11-05'),
  },
    {
    id: 'rev3',
    tourPackageId: 'pkg3',
    userId: 'user8',
    customerName: 'Henry Wilson',
    rating: 3,
    reviewText: 'Interesting cultural tour, but it felt a bit rushed. We could have used more time at each fort. The heritage hotels were a nice touch.',
    createdAt: new Date('2024-03-10'),
  },
];

// Combine into a single export for easier importing
const mockData = {
    tourPackages: mockTourPackages,
    tripDays: mockTripDays,
    tripLocations: mockTripLocations,
    bookings: mockBookings,
    reviews: mockReviews,
};

export default mockData;
