import type { TourPackage, TripDay, TripLocation, Booking, Review, Activity } from './types';

// Helper to generate IDs
const generateId = () => Math.random().toString(36).substr(2, 9);

export const mockTripLocations: TripLocation[] = [
  {
    id: 'loc_everest_base',
    locationName: 'Everest Base Camp',
    latitude: 27.9881,
    longitude: 86.9250,
    type: 'mountain',
    country: 'Nepal',
    state: 'Province No. 1',
    district: 'Solukhumbu',
    city: 'Khumbu',
    code: 'EBC',
    description: 'The starting point for many treks to Mount Everest.',
    address: 'Everest Base Camp, Khumbu, Nepal',
    images: ['https://picsum.photos/seed/loc1/400/300', 'https://picsum.photos/seed/loc1-2/400/300'],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    id: 'loc_goa_beach',
    locationName: 'Calangute Beach',
    latitude: 15.548,
    longitude: 73.759,
    type: 'beach',
    country: 'India',
    state: 'Goa',
    district: 'North Goa',
    city: 'Calangute',
    code: 'GOA-CAL',
    description: 'Famous for its vibrant nightlife and serene beaches.',
    address: 'Calangute Beach, Goa, India',
    images: ['https://picsum.photos/seed/loc2/400/300', 'https://picsum.photos/seed/loc2-2/400/300'],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'loc_jaipur_city_palace',
    locationName: 'Jaipur City Palace',
    latitude: 26.9258,
    longitude: 75.8237,
    type: 'heritage',
    country: 'India',
    state: 'Rajasthan',
    district: 'Jaipur',
    city: 'Jaipur',
    code: 'JAI-CP',
    description: 'A palace complex in Jaipur, the capital of the Rajasthan state.',
    address: 'Tulsi Marg, Gangori Bazaar, J.D.A. Market, Pink City, Jaipur, Rajasthan 302002, India',
    images: ['https://picsum.photos/seed/loc3/400/300'],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'loc_jodhpur_mehrangarh',
    locationName: 'Mehrangarh Fort',
    latitude: 26.2979,
    longitude: 73.0189,
    type: 'heritage',
    country: 'India',
    state: 'Rajasthan',
    district: 'Jodhpur',
    city: 'Jodhpur',
    code: 'JOD-MF',
    description: 'One of the largest forts in India, built in around 1459.',
    address: 'Sodagaran Mohalla, Jodhpur, Rajasthan 342001, India',
    images: ['https://picsum.photos/seed/loc4/400/300'],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'loc_udaipur_lake_pichola',
    locationName: 'Lake Pichola',
    latitude: 24.5707,
    longitude: 73.6749,
    type: 'nature',
    country: 'India',
    state: 'Rajasthan',
    district: 'Udaipur',
    city: 'Udaipur',
    code: 'UDA-LP',
    description: 'An artificial fresh water lake, created in the year 1362 AD.',
    address: 'Lake Pichola, Udaipur, Rajasthan, India',
    images: ['https://picsum.photos/seed/loc5/400/300'],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockActivities: Activity[] = [
    {
        activityId: 'act_arrival_kathmandu',
        name: 'Arrival in Kathmandu & Hotel Check-in',
        type: 'transport',
        time: '02:00 PM',
        duration: '1.5 hours',
        location: 'Kathmandu Airport / Hotel',
        locationId: 'loc_everest_base',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'You will be greeted at the airport and transferred to your hotel.',
    },
    {
        activityId: 'act_gear_check',
        name: 'Gear Check and Briefing',
        type: 'leisure',
        time: '04:00 PM',
        duration: '1 hour',
        location: 'Hotel Lobby',
        locationId: 'loc_everest_base',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'Meet your guide for a full briefing on the trek and a final check of your equipment.',
    },
    {
        activityId: 'act_welcome_dinner',
        name: 'Welcome Dinner',
        type: 'meal',
        time: '07:00 PM',
        duration: '2 hours',
        location: 'Local Nepali Restaurant',
        locationId: 'loc_everest_base',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'Enjoy a traditional Nepali dinner with a cultural show.',
    },
    {
        activityId: 'act_flight_lukla',
        name: 'Fly to Lukla, Trek to Phakding',
        type: 'transport',
        time: '06:30 AM',
        duration: '4 hours',
        location: 'Lukla',
        locationId: 'loc_everest_base',
        price: 0,
        priceIncluded: true,
        bookingRequired: true,
        description: 'An early morning scenic flight to Lukla, followed by a short trek to Phakding.',
    },
    {
        activityId: 'act_phakding_lunch',
        name: 'Lunch in Phakding',
        type: 'meal',
        time: '12:30 PM',
        duration: '1 hour',
        location: 'Phakding',
        locationId: 'loc_everest_base',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'Rest and have lunch at a teahouse in Phakding.',
    },
    {
        activityId: 'act_trek_namche',
        name: 'Trek to Namche Bazaar',
        type: 'trekking',
        time: '08:00 AM',
        duration: '6 hours',
        location: 'On the trail',
        locationId: 'loc_everest_base',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'A challenging trek with rewarding views as you cross suspension bridges and ascend to the Sherpa capital.',
    },
    {
        activityId: 'act_hillary_bridge',
        name: 'Cross Hillary Suspension Bridge',
        type: 'sightseeing',
        time: '11:00 AM',
        duration: '30 minutes',
        location: 'Hillary Bridge',
        locationId: 'loc_everest_base',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'Experience crossing the highest suspension bridge on the EBC trail.',
    },
    {
        activityId: 'act_namche_lunch',
        name: 'Lunch at Namche Bazaar',
        type: 'meal',
        time: '02:00 PM',
        duration: '1 hour',
        location: 'Namche Bazaar',
        locationId: 'loc_everest_base',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'Arrive in Namche and have a well-deserved lunch.',
    },
    {
        activityId: 'act_trek_sunrise',
        name: 'Morning Trek to Viewpoint',
        type: 'trekking',
        time: '06:00 AM',
        duration: '3 hours',
        location: 'Kala Patthar',
        locationId: 'loc_everest_base',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'An early morning trek to catch the sunrise over the Himalayas.',
    },
    {
        activityId: 'act_sherpa_talk',
        name: 'Sherpa Culture Interaction',
        type: 'cultural',
        time: '04:00 PM',
        duration: '1.5 hours',
        location: 'Namche Bazaar',
        locationId: 'loc_everest_base',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'An interactive session with local Sherpas to learn about their culture and mountaineering history.',
    },
    {
        activityId: 'act_acclimatization_hike',
        name: 'Acclimatization Hike',
        type: 'trekking',
        time: '09:00 AM',
        duration: '4 hours',
        location: 'Everest View Hotel',
        locationId: 'loc_everest_base',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'A moderate hike to a higher altitude and back to help the body acclimatize.',
    },
    {
        activityId: 'act_goa_yoga',
        name: 'Beachside Yoga',
        type: 'leisure',
        time: '07:00 AM',
        duration: '1 hour',
        location: 'Calangute Beach',
        locationId: 'loc_goa_beach',
        price: 20,
        priceIncluded: true,
        bookingRequired: true,
        description: 'A relaxing yoga session by the sea.',
    },
    {
        activityId: 'act_dudhsagar_trip',
        name: 'Dudhsagar Falls Excursion',
        type: 'sightseeing',
        time: '08:00 AM',
        duration: 'Full Day',
        location: 'Dudhsagar Falls',
        price: 50,
        priceIncluded: false,
        bookingRequired: true,
        description: 'A full-day trip to the majestic Dudhsagar Falls, including a jeep safari.',
    },
    {
        activityId: 'act_south_goa_tour',
        name: 'South Goa Sightseeing',
        type: 'sightseeing',
        time: '09:30 AM',
        duration: '6 hours',
        location: 'South Goa',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'Visit historic churches, serene beaches, and spice plantations in South Goa.',
    },
    {
        activityId: 'act_jaipur_sightseeing',
        name: 'Jaipur City Tour',
        type: 'sightseeing',
        time: '10:00 AM',
        duration: '8 hours',
        location: 'Jaipur',
        locationId: 'loc_jaipur_city_palace',
        price: 0,
        priceIncluded: true,
        bookingRequired: false,
        description: 'Explore the Pink City, visiting the City Palace, Hawa Mahal, and Jantar Mantar.',
    },
    {
        activityId: 'act_jodhpur_fort_visit',
        name: 'Mehrangarh Fort Exploration',
        type: 'heritage',
        time: '10:00 AM',
        duration: '4 hours',
        location: 'Jodhpur',
        locationId: 'loc_jodhpur_mehrangarh',
        price: 25,
        priceIncluded: false,
        bookingRequired: false,
        description: 'Discover the history and grandeur of one of India\'s most magnificent forts.',
    },
    {
        activityId: 'act_udaipur_boat_ride',
        name: 'Sunset Boat Ride on Lake Pichola',
        type: 'leisure',
        time: '05:00 PM',
        duration: '1.5 hours',
        location: 'Udaipur',
        locationId: 'loc_udaipur_lake_pichola',
        price: 30,
        priceIncluded: true,
        bookingRequired: true,
        description: 'Enjoy a scenic boat ride on Lake Pichola, offering stunning views of the City Palace and Jag Mandir.',
    },
];

export const mockTripDays: TripDay[] = [
  {
    id: 'day_ebc_1',
    dayName: 'Arrival and Preparation',
    dayNumber: 1,
    description: 'Arrive in Kathmandu, check into the hotel, and prepare for the trek ahead.',
    specialInstructions: 'Ensure all your trekking gear is ready and packed.',
    departureLocation: 'Home Country',
    numberOfStays: 1,
    tourPackageId: 'pkg1',
    activities: [
        mockActivities.find(a => a.activityId === 'act_arrival_kathmandu')!,
        mockActivities.find(a => a.activityId === 'act_gear_check')!,
        mockActivities.find(a => a.activityId === 'act_welcome_dinner')!,
    ],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'day_ebc_2',
    dayName: 'Flight to Lukla and Trek to Phakding',
    dayNumber: 2,
    description: 'An exciting scenic flight to Lukla, the gateway to Everest, followed by the first leg of the trek.',
    specialInstructions: 'The flight is weather-dependent. Be prepared for possible delays.',
    departureLocation: 'Kathmandu',
    numberOfStays: 1,
    tourPackageId: 'pkg1',
    activities: [
        mockActivities.find(a => a.activityId === 'act_flight_lukla')!,
        mockActivities.find(a => a.activityId === 'act_phakding_lunch')!,
    ],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'day_ebc_3',
    dayName: 'Trek to Namche Bazaar',
    dayNumber: 3,
    description: 'Trek through beautiful forests and cross suspension bridges to reach the bustling Sherpa town of Namche Bazaar.',
    specialInstructions: 'Watch out for yaks and porters on the trail. Walk slowly and steadily.',
    departureLocation: 'Phakding',
    numberOfStays: 2,
    tourPackageId: 'pkg1',
    activities: [
        mockActivities.find(a => a.activityId === 'act_trek_namche')!,
        mockActivities.find(a => a.activityId === 'act_hillary_bridge')!,
        mockActivities.find(a => a.activityId === 'act_namche_lunch')!,
    ],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'day_goa_1',
    dayName: 'Beach Day & Watersports',
    dayNumber: 1,
    description: 'Enjoy a full day at the famous beaches of Goa. Optional watersports available.',
    specialInstructions: 'Apply sunscreen liberally.',
    departureLocation: 'Goa Airport',
    numberOfStays: 2,
    tourPackageId: 'pkg2',
    activities: [mockActivities.find(a => a.activityId === 'act_goa_yoga')!],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
   {
    id: 'day_goa_2',
    dayName: 'Dudhsagar Falls',
    dayNumber: 2,
    description: 'An exciting day trip to the spectacular Dudhsagar waterfalls.',
    specialInstructions: 'Wear comfortable shoes for a short trek.',
    departureLocation: 'Hotel',
    numberOfStays: 1,
    tourPackageId: 'pkg2',
    activities: [mockActivities.find(a => a.activityId === 'act_dudhsagar_trip')!],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'day_raj_1',
    dayName: 'Arrival in Jaipur',
    dayNumber: 1,
    description: 'Arrive in the Pink City, check into your hotel, and enjoy an evening at leisure.',
    specialInstructions: 'Try the local cuisine for dinner.',
    departureLocation: 'Delhi',
    numberOfStays: 1,
    tourPackageId: 'pkg3',
    activities: [],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'day_raj_2',
    dayName: 'Jaipur Sightseeing',
    dayNumber: 2,
    description: 'A full day exploring the landmarks of Jaipur.',
    specialInstructions: 'Carry a hat and sunglasses.',
    departureLocation: 'Jaipur Hotel',
    numberOfStays: 1,
    tourPackageId: 'pkg3',
    activities: [mockActivities.find(a => a.activityId === 'act_jaipur_sightseeing')!],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'day_raj_3',
    dayName: 'Travel to Jodhpur',
    dayNumber: 3,
    description: 'Morning drive to Jodhpur, the Blue City. Check in and relax.',
    specialInstructions: '',
    departureLocation: 'Jaipur',
    numberOfStays: 1,
    tourPackageId: 'pkg3',
    activities: [],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
   {
    id: 'day_raj_4',
    dayName: 'Jodhpur Fort & Market',
    dayNumber: 4,
    description: 'Visit the magnificent Mehrangarh Fort and explore the bustling Sardar Market.',
    specialInstructions: 'Bargain respectfully at the market.',
    departureLocation: 'Jodhpur Hotel',
    numberOfStays: 1,
    tourPackageId: 'pkg3',
    activities: [mockActivities.find(a => a.activityId === 'act_jodhpur_fort_visit')!],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'day_raj_5',
    dayName: 'Journey to Udaipur',
    dayNumber: 5,
    description: 'Drive to the City of Lakes, Udaipur, en-route visiting the Ranakpur Jain Temples.',
    specialInstructions: 'Dress modestly for the temple visit.',
    departureLocation: 'Jodhpur',
    numberOfStays: 1,
    tourPackageId: 'pkg3',
    activities: [],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'day_raj_6',
    dayName: 'Udaipur Lakes and Palaces',
    dayNumber: 6,
    description: 'Explore the City Palace and enjoy a serene boat ride on Lake Pichola.',
    specialInstructions: 'The boat ride is best enjoyed at sunset.',
    departureLocation: 'Udaipur Hotel',
    numberOfStays: 1,
    tourPackageId: 'pkg3',
    activities: [mockActivities.find(a => a.activityId === 'act_udaipur_boat_ride')!],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];


export const mockTourPackages: TourPackage[] = [
  {
    id: 'pkg1',
    tourName: 'Everest Base Camp Trek',
    tourType: 'international',
    category: 'adventure',
    basePrice: 2500,
    days: 14,
    nights: 13,
    introductionDate: new Date('2023-01-01'),
    withdrawalDate: new Date('2025-01-01'),
    maxPermittedBooking: 15,
    itineraryId: 'itin1',
    imageUrl: 'https://picsum.photos/seed/1/600/400',
    payInParts: [{ partName: 'Deposit', durationMonths: 0, price: 500 }],
    description: 'A challenging and rewarding trek to the base of the world\'s highest mountain.',
    highlights: ['Stunning mountain views', 'Sherpa culture', 'Tengboche Monastery'],
    inclusions: ['Flights from Kathmandu to Lukla', 'Accommodation in tea houses', 'Licensed guide'],
    exclusions: ['International airfare', 'Personal trekking gear', 'Tips for guides'],
    bookingPolicies: 'A 20% deposit is required at the time of booking.',
    cancellationPolicies: 'Cancellations made 30 days prior to departure are fully refundable.',
    termsAndConditions: 'Travel insurance is mandatory for all participants.',
    isFeatured: true,
    featuredImageUrl: 'https://picsum.photos/seed/2/1200/800',
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'pkg2',
    tourName: 'Goa Beach Paradise',
    tourType: 'domestic',
    category: 'leisure',
    basePrice: 800,
    days: 5,
    nights: 4,
    introductionDate: new Date('2023-03-01'),
    withdrawalDate: new Date('2024-12-31'),
    maxPermittedBooking: 50,
    itineraryId: 'itin2',
    imageUrl: 'https://picsum.photos/seed/3/600/400',
    payInParts: [],
    description: 'Relax and unwind on the beautiful beaches of Goa.',
    highlights: ['Pristine beaches', 'Vibrant nightlife', 'Portuguese architecture'],
    inclusions: ['Accommodation in a 4-star hotel', 'Daily breakfast', 'Airport transfers'],
    exclusions: ['Airfare', 'Lunches and dinners', 'Watersports activities'],
    bookingPolicies: 'Full payment is required at the time of booking.',
    cancellationPolicies: 'Non-refundable.',
    termsAndConditions: 'Subject to availability.',
    isFeatured: false,
    featuredImageUrl: '',
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    id: 'pkg3',
    tourName: 'Cultural Rajasthan',
    tourType: 'domestic',
    category: 'cultural',
    basePrice: 1200,
    days: 7,
    nights: 6,
    introductionDate: new Date('2023-02-15'),
    withdrawalDate: new Date('2025-02-14'),
    maxPermittedBooking: 25,
    itineraryId: 'itin3',
    imageUrl: 'https://picsum.photos/seed/4/600/400',
    payInParts: [],
    description: 'Explore the vibrant culture and majestic forts of Rajasthan.',
    highlights: ['Jaipur City Palace', 'Jodhpur Mehrangarh Fort', 'Udaipur Lake Pichola'],
    inclusions: ['Accommodation in heritage hotels', 'Private car and driver', 'Local guides'],
    exclusions: ['Entrance fees to monuments', 'Meals', 'Flights'],
    bookingPolicies: '50% payment to book.',
    cancellationPolicies: 'Free cancellation up to 15 days before travel.',
    termsAndConditions: 'Valid for Indian citizens only.',
    isFeatured: true,
    featuredImageUrl: 'https://picsum.photos/seed/5/1200/800',
    status: 'inactive',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'book1',
    tourPackageId: 'pkg1',
    userId: 'user1',
    customerName: 'Alice Johnson',
    customerEmail: 'alice@example.com',
    status: 'confirmed',
    paymentType: 'full',
    transactionId: 'txn_12345',
    reservationDate: new Date(),
    travelDate: new Date('2024-10-15'),
    referralCode: '',
    totalAmount: 2500,
    paidAmount: 2500,
    numberOfTravelers: 1,
    createdAt: new Date(),
  },
  {
    id: 'book2',
    tourPackageId: 'pkg2',
    userId: 'user2',
    customerName: 'Bob Smith',
    customerEmail: 'bob@example.com',
    status: 'pending',
    paymentType: 'partial',
    transactionId: 'txn_67890',
    reservationDate: new Date(),
    travelDate: new Date('2024-11-20'),
    referralCode: 'FRIEND10',
    totalAmount: 1600,
    paidAmount: 800,
    numberOfTravelers: 2,
    createdAt: new Date(),
  },
   {
    id: 'book3',
    tourPackageId: 'pkg2',
    userId: 'user3',
    customerName: 'Charlie Brown',
    customerEmail: 'charlie@example.com',
    status: 'completed',
    paymentType: 'full',
    transactionId: 'txn_abcde',
    reservationDate: new Date('2023-12-01'),
    travelDate: new Date('2024-01-10'),
    referralCode: '',
    totalAmount: 800,
    paidAmount: 800,
    numberOfTravelers: 1,
    createdAt: new Date('2023-12-01'),
  },
    {
    id: 'book4',
    tourPackageId: 'pkg3',
    userId: 'user4',
    customerName: 'Diana Prince',
    customerEmail: 'diana@example.com',
    status: 'cancelled',
    paymentType: 'partial',
    transactionId: 'txn_fghij',
    reservationDate: new Date('2024-02-01'),
    travelDate: new Date('2024-04-05'),
    referralCode: '',
    totalAmount: 2400,
    paidAmount: 1200,
    numberOfTravelers: 2,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'book5',
    tourPackageId: 'pkg1',
    userId: 'user5',
    customerName: 'Ethan Hunt',
    customerEmail: 'ethan@example.com',
    status: 'confirmed',
    paymentType: 'full',
    transactionId: 'txn_klmno',
    reservationDate: new Date(),
    travelDate: new Date('2024-10-15'),
    referralCode: '',
    totalAmount: 2500,
    paidAmount: 2500,
    numberOfTravelers: 1,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
  },
  {
    id: 'book6',
    tourPackageId: 'pkg2',
    userId: 'user6',
    customerName: 'Fiona Glenanne',
    customerEmail: 'fiona@example.com',
    status: 'confirmed',
    paymentType: 'full',
    transactionId: 'txn_pqrst',
    reservationDate: new Date(),
    travelDate: new Date('2024-11-20'),
    referralCode: '',
    totalAmount: 1600,
    paidAmount: 1600,
    numberOfTravelers: 2,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
  },
];

export const mockReviews: Review[] = [
  {
    id: 'rev1',
    tourPackageId: 'pkg2',
    userId: 'user3',
    customerName: 'Charlie Brown',
    rating: 5,
    reviewText: 'Absolutely fantastic trip! The beaches were pristine and the hotel was excellent. Highly recommended for a relaxing getaway.',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'rev2',
    tourPackageId: 'pkg1',
    userId: 'user7',
    customerName: 'Grace Lee',
    rating: 4,
    reviewText: 'The Everest trek was challenging but the views were worth every step. The guide was knowledgeable but some of the tea houses were very basic.',
    createdAt: new Date('2023-11-05'),
  },
    {
    id: 'rev3',
    tourPackageId: 'pkg3',
    userId: 'user8',
    customerName: 'Henry Wilson',
    rating: 3,
    reviewText: 'Interesting cultural tour, but it felt a bit rushed. We could have used more time at each fort. The heritage hotels were a nice touch.',
    createdAt: new Date('2024-03-10'),
  },
];

// Combine into a single export for easier importing
const mockData = {
    tourPackages: mockTourPackages,
    tripDays: mockTripDays,
    tripLocations: mockTripLocations,
    bookings: mockBookings,
    reviews: mockReviews,
};

export default mockData;
